### ISSUE TITLE
Documentation gets not updated automatically

### ISSUE THREAD

**Issue by maxbertrand1996** [trixi-framework/TrixiBottomTopography.jl#15]
Since I transferred this repository from my personal account to `trixi-framework`, the documentation seems to not get updated by itself although the files in `docs/src` have been adjusted. 
Looking into the `Actions` tab of this repo, I saw that the **Doc Preview Cleanup** seems to be failing, because it does not have permission to push `gh-pages` to `origin`.

Does anybody know how to fix this?

I also noticed that in `DocPreviewCleanup.yml` and `Documenter.yml` we still have `checkout@v2` instead of `checkout@v3` as in `ci.yml`. Does his maybe have an impact?

**Comment by sloede** [comment]
The repository does not seem to have a secret `DOCUMENTER_KEY` that is used in the GH action scripts. Have you maybe forgotten to add it after migrating the repo to its new home?

**Comment by andrewwinters5000** [comment]
I briefly looked through the instructions [here](https://github.com/JuliaDocs/Documenter.jl/blob/master/docs/src/man/hosting.md) and I believe one uses the key generator in `DocumenterTools` to create the key and then add it into a hidden part of the repo. From my understanding one of the `trixi-framework` main developers needs to do this because others will not ahve the correct access permissions. Is that right @sloede ?

**Comment by sloede** [comment]
You can have a look at the Documenter.jl docs [here](https://documenter.juliadocs.org/stable/man/hosting/#GitHub-Actions) and [here](https://documenter.juliadocs.org/stable/man/hosting/#Authentication:-SSH-Deploy-Keys). Since @maxbertrand1996 is a maintainer in this repo, he should be able to do this himself (otherwise you'd have to do it, @andrewwinters5000 👍).

**Comment by maxbertrand1996** [comment]
I tried to follow the instructions and got to this point:
![Keys](https://user-images.githubusercontent.com/101979498/206184709-36aabf7b-a4e6-43fd-a2aa-f093ad1d5133.PNG)

But as soon as I pressed `Add key` , this appeared:
![404](https://user-images.githubusercontent.com/101979498/206184724-37a82649-481c-4e19-bef6-701924b12b0e.PNG)

**Comment by maxbertrand1996** [comment]
Thanks a lot. Sadly, it still seems that it did not work...

**Comment by andrewwinters5000** [comment]
Hmm, that is unfortunate. @sloede Do I need to update any of the `.github/workflow` files or something?

**Comment by maxbertrand1996** [comment]
@andrewwinters5000 are you able to open https://github.com/trixi-framework/TrixiBottomTopography.jl/settings/secrets? Because if I try it, I get the same 404 error as before.

**Comment by sloede** [comment]
THere seem to be errors (warnings) in the documentation build: https://github.com/trixi-framework/TrixiBottomTopography.jl/actions/runs/3636685269/jobs/6136890647

Maybe this is the reason why it is not deployed? Maybe try to fix in a PR and set `strict=true` in https://github.com/trixi-framework/TrixiBottomTopography.jl/blob/012686132cd356add28d88372ff6fc4cac9ecfc9/docs/make.jl#L29?

**Comment by maxbertrand1996** [comment]
Ok, I will try it.

**Comment by maxbertrand1996** [comment]
It works now 🎉

**Comment by maxbertrand1996** [comment]
Thanks a lot for your help!
